# Generated by Django 2.2.2 on 2019-07-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, default='', help_text='(optional)', max_length=40, verbose_name='patronymic'),
        ),
    ]
