# Generated by Django 2.2.2 on 2019-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20190705_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_join',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
