# Generated by Django 2.2.2 on 2019-07-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20190705_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='on_black_list',
        ),
    ]
