# Generated by Django 2.2.2 on 2019-07-14 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_message_date_of_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatsListCurrentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_last_message', to='MainApp.Message')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_last_message_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_last_message_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
