# Generated by Django 2.2.2 on 2019-07-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_chatslistcurrentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatslistcurrentmessage',
            name='date_of_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
